### ISSUE TITLE
Re-compile config-tool to avoid confusion for people using the spoof

### ISSUE THREAD

**Issue by Infecta** [Gladuin/iidx-controller#11]
So, I was using the config tool that was on the [releases section](https://github.com/Gladuin/iidx-controller/releases/tag/v1.1).
Then I realized that my controller didn't get detected, after an hour I decided to run the config tool from source instead; and it worked.

I then decided to compare the code that got released for v1.1 and the latest commit and discovered this

(Left is the source from the [releases section](https://github.com/Gladuin/iidx-controller/releases/tag/v1.1) and Right is the latest commit)

![image](https://github.com/Gladuin/iidx-controller/assets/34395934/bce1d6a2-3ff2-4e02-b748-93faca6ceeba)

I don't think there's much needed to be said here now

**Comment by luuk00000000000000000000000000000000000** [comment]
Thanks for giving me the heads up! I think I compiled that release before actually merging the pr that fixed it...
The releases section should now have the correct version. If not, please let me know!
