### ISSUE TITLE
LED always on ?

### ISSUE THREAD

**Issue by RodentVienna** [Gladuin/iidx-controller#8]
Hello,

please bear with me, my issue may be due to me not understanding Gladuin and HID LED in IIDX entirely.

My issue:
When i connect the Gladuin-powered IIDX controller to PC USB, all LED light up constantly.
The desired behaviour however is, that the LED are off, unless a corressponding button is pressed.

What do I actually miss here?

If there is a discord or any other resource available pls let me know.

Thx for any help in advance!
Alex

**Comment by RodentVienna** [comment]
resolved. 
I wired LEDs the opposite way. correct wiring is mentioned in readme tho.
my apologies for this pointless issue creation.
Alex

**Comment by luuk00000000000000000000000000000000000** [comment]
Hi Alex,
Glad to see that you were able to resolve the issue, everyone makes mistakes :)
